"""empty message

Revision ID: 27e8fef6e9cb
Revises: d426272ed514
Create Date: 2021-07-25 06:39:27.086815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e8fef6e9cb'
down_revision = 'd426272ed514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('comissao_percentual', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('produto', 'imagem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('imagem', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('produto', 'comissao_percentual')
    # ### end Alembic commands ###
