"""empty message

Revision ID: 5046c9c02339
Revises: a73bcfc9a549
Create Date: 2021-07-25 11:32:05.618153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5046c9c02339'
down_revision = 'a73bcfc9a549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrinho', sa.Column('venda', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'carrinho', 'venda', ['venda'], ['id'])
    op.drop_constraint('venda_carrinho_fkey', 'venda', type_='foreignkey')
    op.drop_column('venda', 'carrinho')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venda', sa.Column('carrinho', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('venda_carrinho_fkey', 'venda', 'carrinho', ['carrinho'], ['id'])
    op.drop_constraint(None, 'carrinho', type_='foreignkey')
    op.drop_column('carrinho', 'venda')
    # ### end Alembic commands ###
