"""empty message

Revision ID: a73bcfc9a549
Revises: 27e8fef6e9cb
Create Date: 2021-07-25 10:50:56.179696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73bcfc9a549'
down_revision = '27e8fef6e9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carrinho_venda_fkey', 'carrinho', type_='foreignkey')
    op.drop_column('carrinho', 'venda')
    op.add_column('venda', sa.Column('carrinho', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venda', 'carrinho', ['carrinho'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venda', type_='foreignkey')
    op.drop_column('venda', 'carrinho')
    op.add_column('carrinho', sa.Column('venda', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('carrinho_venda_fkey', 'carrinho', 'venda', ['venda'], ['id'])
    # ### end Alembic commands ###
