"""empty message

Revision ID: a9ffa30220d5
Revises: 5046c9c02339
Create Date: 2021-07-25 16:26:44.655985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ffa30220d5'
down_revision = '5046c9c02339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrinho', sa.Column('comissao', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrinho', 'comissao')
    # ### end Alembic commands ###
