"""empty message

Revision ID: aac5c9b25d0a
Revises: 213e071c6ee0
Create Date: 2021-07-24 07:20:30.617563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac5c9b25d0a'
down_revision = '213e071c6ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrinho', sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrinho', 'valor')
    # ### end Alembic commands ###
