"""empty message

Revision ID: db94f60118dc
Revises: a9ffa30220d5
Create Date: 2021-07-25 22:18:02.534142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db94f60118dc'
down_revision = 'a9ffa30220d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carrinho_venda_fkey', 'carrinho', type_='foreignkey')
    op.create_foreign_key(None, 'carrinho', 'venda', ['venda'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carrinho', type_='foreignkey')
    op.create_foreign_key('carrinho_venda_fkey', 'carrinho', 'venda', ['venda'], ['id'])
    # ### end Alembic commands ###
